# Generated by rust2rpm
# Not all deps are packaged
%bcond_with check
%global debug_package %{nil}

%global crate yup-oauth2

Name:           rust-%{crate}
Version:        1.0.11
Release:        3%{?dist}
Summary:        Oauth2 implementation

# Upstream license specification: MIT OR Apache-2.0
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/yup-oauth2
Source:         %{crates_source}
# Initial patched metadata
# * No rustls
Patch0:         yup-oauth2-fix-metadata.diff

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
BuildRequires:  (crate(base64/default) >= 0.10.0 with crate(base64/default) < 0.11.0)
BuildRequires:  (crate(chrono/default) >= 0.4.0 with crate(chrono/default) < 0.5.0)
BuildRequires:  (crate(hyper-native-tls/default) >= 0.3.0 with crate(hyper-native-tls/default) < 0.4.0)
BuildRequires:  (crate(hyper/default) >= 0.10.2 with crate(hyper/default) < 0.11.0)
BuildRequires:  (crate(itertools/default) >= 0.8.0 with crate(itertools/default) < 0.9.0)
BuildRequires:  (crate(log/default) >= 0.3.0 with crate(log/default) < 0.4.0)
BuildRequires:  (crate(openssl/default) >= 0.10.0 with crate(openssl/default) < 0.11.0)
BuildRequires:  (crate(serde/default) >= 1.0.0 with crate(serde/default) < 2.0.0)
BuildRequires:  (crate(serde_derive/default) >= 1.0.0 with crate(serde_derive/default) < 2.0.0)
BuildRequires:  (crate(serde_json/default) >= 1.0.0 with crate(serde_json/default) < 2.0.0)
BuildRequires:  (crate(url/default) >= 1.0.0 with crate(url/default) < 2.0.0)
%if %{with check}
BuildRequires:  (crate(getopts/default) >= 0.2.0 with crate(getopts/default) < 0.3.0)
BuildRequires:  (crate(open/default) >= 1.1.0 with crate(open/default) < 2.0.0)
BuildRequires:  (crate(yup-hyper-mock/default) >= 2.0.0 with crate(yup-hyper-mock/default) < 3.0.0)
%endif

%global _description \
An oauth2 implementation, providing the 'device', 'service account' and\
'installed' authorization flows.

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE-MIT LICENSE-APACHE
%doc README.md changelog.md
%{cargo_registry}/%{crate}-%{version}/
%exclude %{cargo_registry}/%{crate}-%{version}/etc

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+openssl-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+openssl-devel %{_description}

This package contains library source intended for building other packages
which use "openssl" feature of "%{crate}" crate.

%files       -n %{name}+openssl-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.11-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.11-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Tue Feb 12 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.11-1
- Update to 1.0.11

* Sun Feb 10 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.9-5
- Update itertools to 0.8

* Sun Feb 10 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.9-4
- Update base64 to 0.10

* Sat Feb 02 2019 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.9-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_30_Mass_Rebuild

* Tue Nov 27 2018 Josh Stone <jistone@redhat.com> - 1.0.9-2
- Adapt to new packaging

* Thu Oct 11 2018 Josh Stone <jistone@redhat.com> - 1.0.9-1
- Update to 1.0.9

* Sat Jul 28 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.8-1
- Update to 1.0.8

* Wed Jul 25 2018 Igor Gnatenko <i.gnatenko.brain@gmail.com> - 1.0.7-1
- Initial package
